### PR TITLE
Add virtual environment instructions

### PR DESCRIPTION
**Pull request by danniel**
Added details to the Installation process on how to create and activate a Python3 virtual environment. A virtual environment is recommended so that project-specific libraries do not interfere with the system Python libraries (https://docs.python.org/3/tutorial/venv.html).

### CODE REVIEW

**Comment by catileptic** [comment]
Your pull request paints the `venv` as a mandatory component, which it is not. If you want to add this to the README, which is an initiative we really appreciate, please phrase it as a optional step, not a mandatory step.

**Comment by danniel** [comment]
Ok. I have updated the text.

**Comment by lucianoprea** [comment]
Would be nice also the `venv/` directory to be liste in `.gitignore` also as part of this PR.

**Comment by tudoramariei** [comment]
> Would be nice also the `venv/` directory to be liste in `.gitignore` also as part of this PR.

It actually is listed. You can check the changed files :)

**Comment by lucianoprea** [comment]
> > Would be nice also the `venv/` directory to be liste in `.gitignore` also as part of this PR.
> 
> It actually is listed. You can check the changed files :)

My bad, I only saw the last commit.

**Pull request merged**
